=== edvilme/BT2-Ocupacion-IOT/Dashboard/Floor.schema.json
{
    "$schema": "http://json-schema.org/schema", 
    "$id": "FloorPlan.schema.json", 
    "description": "JSON Schema used to store information about a floor, including its floor plan, areas and data", 
    "properties": {
        "id": {
            "description": "Unique identifier of each floor. Useful in the context of a building or campus.", 
            "type": "string"
        },
        "name": {
            "description": "Conventional name of the floor. Should be easily identifiable to users", 
            "type": "string"
        }, 
        "dwgFile": {
            "description": "Path to .dwg file containg architectural floor plan and distribution.", 
            "type": "string"
        }, 
        "svgFile": {
            "description": "Path to .svf file containing architectural floor plan and distribution.",
            "type": "string"
        },
        "boundingBox": {
            "description": "Coordinates for svg bounding box. Used when rendering maps",
            "type": "array", 
            "maxLength": 2,
            "items": {
                "type": "array", 
                "maxLength": 2, 
                "items": {
                    "type": "number"
                }
            } 
        }, 
        "spaces": {
            "description": "Array of spaces inside this floor",
            "type": "array", 
            "items": {
                "properties": {
                    "id": {
                        "description": "Unique identifier of each space inside the floor", 
                        "type": "string"
                    }, 
                    "name": {
                        "description": "Conventional name of the space inside the floor", 
                        "type": "string"
                    }, 
                    "category": {
                        "description": "Category of space (eg, conference room, cubicle, personal office). Categories vary according to client's criteria", 
                        "type": "string"
                    }, 
                    "vertices": {
                        "description": "Array of vertices defining the points inside the floor", 
                        "type": "array", 
                        "items": {
                            "type": "array", 
                            "maxItems": 2, 
                            "items": {
                                "type": "number"
                            }
                        }, 
                        "maxItems": 2
                    }
                }, 
                "required": ["id", "name", "vertices"]
            }
        }
    }, 
    "required": ["id", "name", "spaces"]
}

=== edvilme/BT2-Ocupacion-IOT/Dashboard-old/data/rectoriaITESM-4.json
{
    "$schema": "../Floor.schema.json",
    "id": "rectoriaITESM-4", 
    "boundingBox": [[0, 0], [800, 600]], 
    "name": "Rectoria Piso 4", 
    "spaces": [
        {
            "id": "rectoriaITESM-4.01", 
            "name": "Sala de espera", 
            "vertices": [
                [306.21722412109375, 201.27340698242188],
                [306.21722412109375, 416.40447998046875],
                [497.9775390625, 202.47190856933594],
                [497.9775390625, 417.6029968261719]
            ] 
        },
        {
            "id": "rectoriaITESM-04.02", 
            "name": "Asistentes rectoria", 
            "vertices": [
                [175.5805206298828, 119.17603302001953],
                [172.5842742919922, 197.6779022216797],
                [381.72283935546875, 199.4756622314453],
                [381.12359619140625, 118.5767822265625]
            ]
        }
    ]
}
